version: '3'

services:
  web:
    env_file: .env
    environment:
      - EX_PORT_NGINX=$EX_PORT_NGINX
      - PORT_NGINX=$PORT_NGINX
    image: nginx:alpine
    restart: always
    ports:
      - "$EX_PORT_NGINX:$PORT_NGINX"
    volumes:
      - ./src:/code
      - ./log:/log
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - django
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  django:
    env_file: .env
    environment:
      - GUNICORN_PORT=$GUNICORN_PORT
    build: 
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:${GUNICORN_PORT}
    volumes:
      - ./src/app:/home/app/web/app
      - ./src/config:/home/app/web/config
      - ./src/utils:/home/app/web/utils
      - ./src/templates:/home/app/web/templates
      - ./src/log:/home/app/web/log
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
networks:
  default:
    external:
      name: django-template

volumes:
  static_volume:
  media_volume:

      